### ISSUE TITLE
Django CI #24

### ISSUE THREAD

**Issue by Lamonkey** [joshuam1008/media-analyzer#13]
secrete key is empty

**Comment by Lamonkey** [comment]
secrete key in settings is removed for production on the main branch. Once set it up this issue should be resolved

**Comment by david12white** [comment]
Secret key was just added using Github's repository feature. We still have one more CI issue, debugging now.

**Comment by david12white** [comment]
Issue involved trying to configure heroku settings outside of deployment. Issue resolved.
