### ISSUE TITLE
Sentiment Model CPU Support

### ISSUE THREAD

**Issue by cjdolan** [joshuam1008/media-analyzer#15]
**Describe the bug**
When the machine running the model does not have CUDA enabled the model fails to make inference.

**To Reproduce**
1. Load the repo on a machine with CUDA disabled
2. Call the inference function from the inference class

**Expected behavior**
The program will return an error saying pytorch is not compiled with CUDA enabled

**Comment by david12white** [comment]
I believe the script should use GPU when available and CPU when not.

**Comment by cjdolan** [comment]
The code now defaults to using CPU for inference.
