### ISSUE TITLE
Start Stream/Stop Stream have identical functionality, altering based on current state

### ISSUE THREAD

**Issue by david12white** [joshuam1008/media-analyzer#18]
**Describe the bug**
Stop and start stream both toggle the module, disconnecting or connecting to the stream based on the current state.

**To Reproduce**
1. Go to the deployment/run the code
2. Click start stream/stop stream
3. Observe behavior of function calls and stream

**Expected behavior**
Start stream should either connect to the stream or do nothing, while stop stream should either disconnect or do nothing.

**Comment by rohanssrao** [comment]
Fixed by using one button to toggle between start and stop. Two buttons are not needed.
