### ISSUE TITLE
test_homepage failing

### ISSUE THREAD

**Issue by david12white** [joshuam1008/media-analyzer#3]
**Describe the bug**
Template Homepage test failing.

**To Reproduce**
1. Request ('/') from the server

Also in github actions.

**Expected behavior**
The home page should populate.

**Comment by Lamonkey** [comment]
Did you use render. if you use render you have to config static folder for Django and have the corresponded HTML in the static folder

**Comment by Lamonkey** [comment]
fixed by modifying *.yml file by removing pip freeze and config static root directory in settings.py
