### ISSUE TITLE
Error handling for lang detect

### ISSUE THREAD

**Issue by Lamonkey** [joshuam1008/media-analyzer#36]
lang detect need error handling, when pass in language it can't recognize it will raise an exception

**Comment by joshuam1008** [comment]
Should `LangModule`'s `generate_result` return None if the language isn't recognized?

**Comment by Lamonkey** [comment]
I think "error" maybe better, None currently been used as a place holder for result will be processed later

**Comment by joshuam1008** [comment]
Error handling was added and tested in `test_analyzers.py`
