### ISSUE TITLE
Failing Tests: HTTP 429 Error

### ISSUE THREAD

**Issue by david12white** [joshuam1008/media-analyzer#56]
**Describe the bug**
Stream gets 429 error, causing scheduler to throw exceptions.

**To Reproduce**
1. Run the Tests in Github actions

**Comment by rohanssrao** [comment]
This occurs when a [rate limit](https://developer.twitter.com/en/docs/twitter-api/rate-limits) happens or if there are two simultaneous running instances of the server, trying to access the API with the same token.

**Solution**

This is mainly out of our control. Avoid running two instances simultaneously.
