### ISSUE TITLE
Add Linux Kernel Best Practices document

### ISSUE THREAD

**Issue by rohanssrao** [joshuam1008/media-analyzer#60]
Write a 2 page pdf on the connection between the items in the rubric and the Linux Kernel best practices. Add that document to the repo as `docs/proj1rubricComments.pdf`.

[Linux Kernel Best Practices](https://go.pardot.com/l/6342/2017-10-24/3xr3f2/6342/188781/Publication_LinuxKernelReport_2017.pdf) (see pages 25,26)

**Comment by david12white** [comment]
Collaborated with @joshuam1008 on document. Added to main.
